### ISSUE TITLE
Update to use React Transform

### ISSUE THREAD

**Issue by Haemoglobin** [alexgorbatchev/gulp-typescript-webpack-react-hotreload#1]
react-hot-loader has now been replaced with react-transform (https://github.com/gaearon/react-transform-boilerplate) - would be good to see this example updated to work with that.

**Comment by alexgorbatchev** [comment]
Thanks for bringing this up, I didn't know `react-hot-loader` was being deprecated. I'm not sure if I'm currently able to use `react-transform-hmr` because it seems to require Babel and no longer works as webpack loader.

**Comment by Haemoglobin** [comment]
Seems possible, you can take inspiration from https://github.com/wmaurer/react-transform-boilerplate-ts or https://github.com/keokilee/react-typescript-boilerplate 
I haven't had huge success with it so far however...



    _____________________________

**Comment by Haemoglobin** [comment]
Just saw your question to Dan, +1 if you can figure out how to get it working without a Babel dependency!!

**Comment by alexgorbatchev** [comment]
Seems like 3 months later it's still in the very "experimental" state, whatever that means. I feel that at the moment the original webpack HMR is battle proven and works well.

**Comment by mquandalle** [comment]
A major update to react-hot-loader is coming: https://github.com/gaearon/react-hot-boilerplate/pull/61

**Comment by alexgorbatchev** [comment]
I updated to use `react-transform-hmr` and babel, works great so far, I like it much better.
