### ISSUE TITLE
gulp-tslint requires tslint

### ISSUE THREAD

**Issue by nupplaphil** [alexgorbatchev/gulp-typescript-webpack-react-hotreload#4]
Hi,

In
https://github.com/panuhorsmalahti/gulp-tslint/blob/master/package.json
there is a peerDependencie to tslint
>  "peerDependencies": {
>     "tslint": "^3 || >=3.1.0-dev || >=3.2.0-dev || >=3.2.1-dev || >= 3.2.2-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.7.0-dev"
>   },

I had to install tslint with "--save-dev" to be able to install gulp-tslint

**Comment by alexgorbatchev** [comment]
Thanks, I updated `package.json`
